[target.aarch64-unknown-linux-gnu]
image = "aarch64-unknown-linux-gnu"
[target.armv7-unknown-linux-gnueabihf]
image = "armv7-unknown-linux-gnueabihf"
#[target.riscv64gc-unknown-linux-gnu]
#image = "ghcr.io/slint-ui/slint/riscv64gc-unknown-linux-gnu"
#[target.x86_64-unknown-linux-gnu]
#image = "ghcr.io/slint-ui/slint/x86_64-unknown-linux-gnu"

[build.env]
passthrough = [
    "SLINT_NO_QT",
    "SLINT_STYLE",
    "SLINT_TEST_FILTER",
    "SLINT_INTERPRETER_ERROR_WHITELIST",
]