export global Images {
    in property <image> settings: @image-url("assets/images/settings.svg");
    in property <image> phone: @image-url("assets/images/phone.svg");
    in property <image> media: @image-url("assets/images/media.svg");
    in property <image> message: @image-url("assets/images/message.svg");
    in property <image> home: @image-url("assets/images/home.svg");
    in property <image> camera: @image-url("assets/images/camera.svg");
    in property <image> seat-right: @image-url("assets/images/seat_right.svg");
    in property <image> seat-left: @image-url("assets/images/seat_left.svg");
    in property <image> arrow-up: @image-url("assets/images/arrow_up.svg");
    in property <image> arrow-down: @image-url("assets/images/arrow_down.svg");
    in property <image> navigation: @image-url("assets/images/navigation.svg"); 
}