export global Images {
    in property <image> settings: @image-url("assets/images/settings.svg");
    in property <image> phone: @image-url("assets/images/phone.svg");
    in property <image> media: @image-url("assets/images/media.svg");
    in property <image> message: @image-url("assets/images/message.svg");
    in property <image> home: @image-url("assets/images/home.svg");
    in property <image> camera: @image-url("assets/images/camera.svg");
    in property <image> seat-right: @image-url("assets/images/seat_right.svg");
    in property <image> seat-left: @image-url("assets/images/seat_left.svg");
    in property <image> arrow-up: @image-url("assets/images/arrow_up.svg");
    in property <image> arrow-down: @image-url("assets/images/arrow_down.svg");
    in property <image> navigation: @image-url("assets/images/navigation.svg");
    in property <image> emergency-triangle: @image-url("assets/images/emergency_triangle.svg");
    in property <image> headlights: @image-url("assets/images/headlights.svg");
    in property <image> key: @image-url("assets/images/key.svg");
    in property <image> car: @image-url("assets/images/car.png");
    in property <image> car-light: @image-url("assets/images/car-light.png");
    in property <image> car-headlights: @image-url("assets/images/car_headlights.svg");
    in property <image> car-emergency: @image-url("assets/images/car-emergency.png");
    in property <image> album: @image-url("assets/images/album.jpg");
    in property <image> player-prev: @image-url("assets/images/player/prev.svg");
    in property <image> player-next: @image-url("assets/images/player/next.svg");
    in property <image> player-pause: @image-url("assets/images/player/pause.svg");
    in property <image> weather-cloudy: @image-url("assets/images/weather/cloudy.svg");
    in property <image> map-plus: @image-url("assets/images/map/plus.svg");
    in property <image> map-minus: @image-url("assets/images/map/minus.svg");
}
