import { Theme } from "theme.slint";
import { MainPage } from "views/main.slint";
import { Button , Slider, CheckBox} from "std-widgets.slint";

// import "assets/fonts/Poppins-Regular.ttf";
// import "assets/fonts/Poppins-Medium.ttf";
// import "assets/fonts/Poppins-SemiBold.ttf";

export global MainWindowAdapter {
    in property <length> height;
    in property <length> width;
}

export component Test {
    height: 34px;
}

export component MainWindow inherits Window {
    title: "Car Dashboard";
    min-width: 1440px;
    min-height: 1024px;
    preferred-height: MainWindowAdapter.height;
    preferred-width: MainWindowAdapter.width;

    // default-font-family: "Poppins";
    background: Theme.palette.background;

    MainPage {
        // width: 1440px;
                     // height: 1024px;
    }
}
