import { Theme } from "../theme.slint";
import { MenuBar } from "menu_bar.slint";
import { Header } from "header.slint";
import { Radio } from "radio.slint";
import { Car } from "car.slint";
import { Button, GridBox, HorizontalBox } from "std-widgets.slint";

export component MainPage inherits Rectangle {
    animate background { duration: 300ms; }
    out property <length> map_visible_width: radio.map_visible_width;
    out property <length> map_visible_height: radio.map_visible_width;

    VerticalLayout {
        padding: 20px;

        HorizontalLayout {
            spacing: 20px;
            padding-bottom: 20px;

            car := Car {
                max-width: 5px;
            }

            radio := Radio {
                active-view: menu-bar.selected-view;
            }
        }

        VerticalLayout {
            menu-bar := MenuBar {
                height: 70px;
            }
        }
    }
}
