import { ViewType } from "types.slint";
import { MenuButton } from "../widgets/menu_button.slint";
import { MenuClimateControl } from "../widgets/menu_climate_control.slint";
import { Images } from "../images.slint";

export component MenuBar inherits HorizontalLayout {
    in-out property <int> selected-view: 0;

    spacing: 15px;

    MenuClimateControl { }

    Rectangle { }

    MenuButton {
        icon: Images.home;
        selected: root.selected-view == 0;
        clicked => {
            root.selected-view = 0;
        }
    }

    MenuButton {
        icon: Images.navigation;
        selected: root.selected-view == 1;
        clicked => {
            root.selected-view = 1;
        }
    }

    MenuButton {
        icon: Images.camera;
        selected: root.selected-view == 2;
        clicked => {
            root.selected-view = 2;
        }
    }

    MenuButton {
        icon: Images.media;
        selected: root.selected-view == 3;
        clicked => {
            root.selected-view = 3;
        }
    }

    MenuButton {
        icon: Images.settings;
        selected: root.selected-view == 4;
        clicked => {
            root.selected-view = 4;
        }
    }

    Rectangle { }

    MenuClimateControl {
        is-right: true;
    }
}
