import { Theme } from "../theme.slint";
import { Images } from "../images.slint";
import { ProgressBar, TrackSlider } from "../widgets/widgets.slint";
import { TransparentIconButton } from "../widgets/icon_button.slint";

export struct Track {
    name: string,
    author: string,
    delay_sec: int,
    cover: image,
}

export global PlayerAdapter {
    in-out property <int> current_index: 0;
    in-out property <Track> current_track: tracklist[current_index];

    property <[Track]> tracklist: [
        {
            name: "Here Comes the Sun",
            author: "The Beatles",
            delay_sec: 120,
            cover: @image-url("../assets/images/player/cover1.jpg"),
        },
        {
            name: "Light My Fire",
            author: "The Doors",
            delay_sec: 140,
            cover: @image-url("../assets/images/player/cover2.jpg"),
        },
        {
            name: "Sacrifice",
            author: "The Weeknd",
            delay_sec: 188,
            cover: @image-url("../assets/images/player/cover3.jpg"),
        },
        {
            name: "Miss You",
            author: "Oliver Tree, Robin Schulz",
            delay_sec: 188,
            cover: @image-url("../assets/images/player/cover4.jpg"),
        },
        {
            name: "Ausländer",
            author: "Rammstein",
            delay_sec: 188,
            cover: @image-url("../assets/images/player/cover5.jpg"),
        }
    ];
    function prev_track() {
        if (current_index == 0) {
            current_index = tracklist.length - 1;
        } else {
            current_index = mod(current_index - 1, tracklist.length);
        }
    }
    function next_track() {
        current_index = mod(current_index + 1, tracklist.length);
    }
}

export component CompactPlayer inherits Rectangle {
    border-radius: 15px;
    background: Theme.palette.view-background;
    animate background { duration: Theme.durations.change-dark-mode; }

    HorizontalLayout {
        padding: 12px;
        spacing: 16px;
        Rectangle {
            width: self.height;
            border-radius: 8px;
            clip: true;
            horizontal-stretch: 0;
            Image {
                width: parent.width;
                height: parent.height;
                source: PlayerAdapter.current_track.cover;
                image-fit: contain;
            }
        }

        Rectangle {
            VerticalLayout {
                alignment: center;
                Text {
                    text: PlayerAdapter.current_track.name;
                    font-size: 16pt;
                    color: Theme.palette.text-color;
                }

                Text {
                    text: PlayerAdapter.current_track.author;
                    font-size: 14pt;
                    color: Theme.palette.text-color;
                    opacity: 0.5;
                }
            }
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        Rectangle {
            HorizontalLayout {
                padding-top: 10px;
                padding-right: 12px;
                padding-bottom: 10px;
                spacing: 12px;
                TransparentIconButton {
                    width: self.height;
                    icon: Images.player-prev;
                    clicked => {
                        PlayerAdapter.prev_track();
                    }
                }

                TransparentIconButton {
                    width: self.height;
                    icon: Images.player-pause;
                }

                TransparentIconButton {
                    width: self.height;
                    icon: Images.player-next;
                    clicked => {
                        PlayerAdapter.next_track();
                    }
                }
            }
        }
    }
}

export component Player inherits Rectangle {
    border-radius: 15px;
    background: Theme.palette.view-background;
    animate background { duration: Theme.durations.change-dark-mode; }

    VerticalLayout {
        padding: 20px;
        spacing: 20px;
        alignment: center;
        Rectangle {
            Rectangle {
                border-radius: 8px;
                clip: true;
                height: 220px;
                width: 220px;
                Image {
                    width: parent.width;
                    height: parent.height;
                    source: PlayerAdapter.current_track.cover;
                    image-fit: contain;
                }
            }
        }

        VerticalLayout {
            alignment: center;
            Text {
                text: PlayerAdapter.current_track.name;
                font-size: 16pt;
                color: Theme.palette.text-color;
                horizontal-alignment: center;
            }

            Text {
                text: PlayerAdapter.current_track.author;
                font-size: 14pt;
                color: Theme.palette.text-color;
                opacity: 0.5;
                horizontal-alignment: center;
            }
        }

        HorizontalLayout {
            padding-left: 60px;
            padding-right: 60px;
            TrackSlider { }
        }

        Rectangle {
            Rectangle {
                height: 120px;
                width: 280px;
                HorizontalLayout {
                    alignment: center;
                    spacing: 12px;
                    padding: 12px;
                    TransparentIconButton {
                        icon: Images.player-prev;
                        clicked => {
                            PlayerAdapter.prev_track();
                        }
                    }

                    TransparentIconButton {
                        icon: Images.player-pause;
                    }

                    TransparentIconButton {
                        icon: Images.player-next;
                        clicked => {
                            PlayerAdapter.next_track();
                        }
                    }
                }
            }
        }
    }
}
