[package]
name = "map-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.5.1", optional = true }

[features]
map-api = []
slint = ["map-api", "dep:slint"]
tiling = ["map-api"]